import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import Popup from "@/app/_components/menu/popup"
import Test from "@/app/_components/test"
import Boot from "./Bootstrap"
import FloatS from "@/app/_client/float_search"
import FloatingWindow from "@/app/_components/floating_window";
import Script from "next/script";

import Window, { WindowTemplate, WindowTemplateColor } from "@/app/_components/window"

import Header from "@/app/_components/header"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="ja">
            <head>
                <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></Script>
            </head>
            <body>
                <Header></Header>
                <div className="container">
                    <Boot></Boot>{/**Bootstrap */}
                    {/* <Test></Test> */}
                    <Popup></Popup>
                    {/* <FloatingWindow id="popup" label="検索結果"
                        windowStyle={{width: "35vw", height: "40vh", minWidth: "300px", opacity: 1, userSelect: "none", display: "flex", flexDirection: "column", borderRadius: "20px", border: "3px solid", overflow: "hidden"}}
                        frameStyle={{backgroundColor: "gray"}}
                        >
                        <Popup_frame id="popup_iframe" customClass="" style={{width: "100%", height: "100%"}}></Popup_frame>
                    </FloatingWindow> */}
                    <Window id="floating_search_window" template={WindowTemplate.floating} templateColor={WindowTemplateColor.monochrome} customWindowStyle={{opacity: 0, pointerEvents: "none"}}>
                        <iframe src="" id="popup_iframe" style={{width: "100%", flex:1, margin: "0px"}}></iframe>
                        {/* <Popup_frame id="popup_iframe" customClass="" style={{width: "100%", height: "100%"}}></Popup_frame> */}
                    </Window>
                    {children}
                </div>
                <FloatS></FloatS>
            </body>
        </html>
    );
}
